app:    
 jwt-secret: MappingSecretKey
 jwt-expiration-in-milliseconds: 1800000 #30 minutes  

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapping_jwt?createDatabaseIfNotExist=true
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
     